# M2 end-to-end demonstration: a hand-written user-packages flake that
# exercises both code paths in lib.importManifest.
#
# Real users get this file generated by `glix init`. Here it is committed
# verbatim so we can prove the contract without depending on the CLI.
{
  description = "glixos example user-packages flake (M2 demo)";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";

    glixos-core = {
      url = "path:../..";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # >>> glix-managed inputs >>>
    pkg-hello = {
      url = "path:../pkg-hello";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    pkg-greeting = {
      url = "path:../pkg-greeting";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    # <<< glix-managed inputs <<<
  };

  outputs = { self, nixpkgs, glixos-core, home-manager, ... }@inputs:
    let
      lib = nixpkgs.lib;

      mkHost = hostName: system:
        let
          manifest = glixos-core.lib.importManifest {
            manifestPath = ./hosts/${hostName}/glix.toml;
            inherit inputs;
          };
        in
        lib.nixosSystem {
          inherit system;
          specialArgs = { inherit inputs manifest; };
          modules = [
            glixos-core.nixosModules.glixos
            home-manager.nixosModules.home-manager
            ./hosts/${hostName}
          ] ++ manifest.systemModules;
        };
    in
    {
      nixosConfigurations.example = mkHost "example" "x86_64-linux";

      checks.x86_64-linux.example-toplevel =
        self.nixosConfigurations.example.config.system.build.toplevel;
    };
}
